# 🧮 Sorting & Filtering in Pandas

## 🔹 LEARNING GOALS:
- Sort rows using `.sort_values()`
- Filter data using conditional logic
- Chain multiple filters together
- Use `.query()` for readable filtering

### 📥 1. Load the Dataset

In [2]:
import pandas as pd

df = pd.read_csv("../../data/students.csv")
df.head()

,Unnamed: 0,first_name,last_name,math_score,science_score,NAME_LENGTH,MATH_PLUS_5
0,0,Alice,Smith,85,88,5,90
1,1,Bob,Jones,90,85,3,95
2,2,Charlie,Brown,78,82,7,83
3,3,David,Wilson,92,95,5,97

### 🔢 2. Sorting Data

In [3]:
# Sort by math_score
df.sort_values(by="math_score")

,Unnamed: 0,first_name,last_name,math_score,science_score,NAME_LENGTH,MATH_PLUS_5
2,2,Charlie,Brown,78,82,7,83
0,0,Alice,Smith,85,88,5,90
1,1,Bob,Jones,90,85,3,95
3,3,David,Wilson,92,95,5,97

In [4]:
# Sort by science_score descending
df.sort_values(by="science_score", ascending=False)

,Unnamed: 0,first_name,last_name,math_score,science_score,NAME_LENGTH,MATH_PLUS_5
3,3,David,Wilson,92,95,5,97
0,0,Alice,Smith,85,88,5,90
1,1,Bob,Jones,90,85,3,95
2,2,Charlie,Brown,78,82,7,83

In [5]:
# Sort by multiple columns
df.sort_values(by=["science_score", "math_score"], ascending=[False, True])

,Unnamed: 0,first_name,last_name,math_score,science_score,NAME_LENGTH,MATH_PLUS_5
3,3,David,Wilson,92,95,5,97
0,0,Alice,Smith,85,88,5,90
1,1,Bob,Jones,90,85,3,95
2,2,Charlie,Brown,78,82,7,83

### 🧪 3. Filtering with Conditions

In [6]:
# Who scored at least 90 in math?
df[df["math_score"] >= 90]

,Unnamed: 0,first_name,last_name,math_score,science_score,NAME_LENGTH,MATH_PLUS_5
1,1,Bob,Jones,90,85,3,95
3,3,David,Wilson,92,95,5,97

In [7]:
# Who scored less than 70 in either subject?
df[(df["math_score"] < 70) | (df["science_score"] < 70)]

Empty DataFrame
Columns: [Unnamed: 0, first_name, last_name, math_score, science_score, NAME_LENGTH, MATH_PLUS_5]
Index: []

### 🔗 4. Combining Filters

In [8]:
# Students with B+ or higher in both
df[(df["math_score"] >= 87) & (df["science_score"] >= 87)]

,Unnamed: 0,first_name,last_name,math_score,science_score,NAME_LENGTH,MATH_PLUS_5
3,3,David,Wilson,92,95,5,97

### 🧾 5. Using `.query()` for Readability

In [9]:
# Same query using .query()
df.query("math_score >= 87 and science_score >= 87")

,Unnamed: 0,first_name,last_name,math_score,science_score,NAME_LENGTH,MATH_PLUS_5
3,3,David,Wilson,92,95,5,97

### 🧪 Try It Yourself

- Sort the dataset by first name alphabetically
- Find students with the same math and science score
- Use `.query()` to find students who scored over 95 in *either* subject

In [11]:
import pandas as pd

df = pd.read_csv("./../../data/students.csv")

df.columns = df.columns.str.replace(" ", "_")

df = df.sort_values("first_name")

same_scores = df[df["math_score"] == df["science_score"]]

high_scores = df.query("math_score > 95 or science_score > 95")

print(df)
print(same_scores)
print(high_scores)

   Unnamed:_0 first_name last_name  math_score  science_score  NAME_LENGTH  \
0           0      Alice     Smith          85             88            5
1           1        Bob     Jones          90             85            3
2           2    Charlie     Brown          78             82            7
3           3      David    Wilson          92             95            5

   MATH_PLUS_5
0           90
1           95
2           83
3           97
Empty DataFrame
Columns: [Unnamed:_0, first_name, last_name, math_score, science_score, NAME_LENGTH, MATH_PLUS_5]
Index: []
Empty DataFrame
Columns: [Unnamed:_0, first_name, last_name, math_score, science_score, NAME_LENGTH, MATH_PLUS_5]
Index: []

### 🧠 Mini-Challenge

> Load `"data/survey.csv"` and:
- Sort by the most recent signup date
- Filter out anyone who didn't complete the survey (nulls or "N/A")
- Use `.query()` to select rows with a specific condition of your choice

In [13]:
import pandas as pd
import numpy as np

df = pd.read_csv("./../../data/survey.csv")

df.columns = df.columns.str.replace(" ", "_")

df = df.replace(["", " ", "N/A", "na", "NA"], np.nan)

date_col = [col for col in df.columns if "date" in col.lower()]
if date_col:
    df[date_col[0]] = pd.to_datetime(df[date_col[0]], errors="coerce")
    df = df.sort_values(date_col[0], ascending=False)

df = df.dropna()

condition_cols = df.select_dtypes(include="number").columns
if len(condition_cols) > 0:
    col = condition_cols[0]
    df_q = df.query(f"{col} > {df[col].median()}")
else:
    df_q = df

print(df)
print(df_q)

Empty DataFrame
Columns: [student_id, age, gender, major, gpa, study_hours_per_week, satisfaction_1_5, survey_date, dorm_resident, expected_grad_year, income_range, commute_minutes, clubs_member, attendance_rate, favorite_language, comments]
Index: []
Empty DataFrame
Columns: [student_id, age, gender, major, gpa, study_hours_per_week, satisfaction_1_5, survey_date, dorm_resident, expected_grad_year, income_range, commute_minutes, clubs_member, attendance_rate, favorite_language, comments]
Index: []

/tmp/ipykernel_93052/805043053.py:12: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[date_col[0]] = pd.to_datetime(df[date_col[0]], errors="coerce")

### 📝 Summary

| Task              | Code Example                                 |
|-------------------|-----------------------------------------------|
| Sort by column     | `df.sort_values(by="col")`                  |
| Filter condition   | `df[df["col"] > value]`                     |
| Combine filters    | `df[(cond1) & (cond2)]`                     |
| Query method       | `df.query("col > value and col2 < value")`  |